name: Build

env:
  GO_VERSION: 1.15
  ATTACHMENTS: ""
  GOPATH: ${{ github.workspace }}

on:
  push:
    release:
      types:
        - created
    branches:
      - master
      - devel
    pull_request:
      branches:
        - master
        - devel

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Chechout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: |
          cd ./src/github.com/${{ github.repository }}/src
          go mod vendor

      - name: Run tests
        env:
          RELEASE_VERSION: ${{ env.GITHUB_REF_SLUG }}
        run: |
          cd ./src/github.com/${{ github.repository }}
          make test

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./src/github.com/${{ github.repository }}/cover.out

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Chechout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: |
          cd ./src/github.com/${{ github.repository }}/src
          go mod vendor

      - name: Build
        env:
          RELEASE_VERSION: ${{ env.GITHUB_REF_SLUG }}
        run: |
          cd ./src/github.com/${{ github.repository }}
          make build-all

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'release' }}
        with:
          name: s3sync-service-${{ env.GITHUB_REF_SLUG }}
          path: ./src/github.com/${{ github.repository }}/s3sync-service-*

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Chechout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker buildx
        env:
          RELEASE_VERSION: ${{ env.GITHUB_REF_SLUG }}
        run: |
          cd ./src/github.com/${{ github.repository }}
          make docker-multi-arch

  docker-quay:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Chechout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Docker buildx
        env:
          RELEASE_VERSION: ${{ env.GITHUB_REF_SLUG }}
          DOCKER_BASE_REPO: quay.io/s3sync-service/s3sync-service
        run: |
          cd ./src/github.com/${{ github.repository }}
          make docker-multi-arch

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs: [build, docker]
    steps:
      - name: Chechout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}

      - name: Set up Hub
        uses: geertvdc/setup-hub@master

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: s3sync-service-${{ env.GITHUB_REF_SLUG }}
          path: artifacts/

      - name: Upload assets
        run: |
          for artifact in $(ls artifacts/*); do ATTACHMENTS="${ATTACHMENTS} -a ${artifact}"; done;
          hub release edit -m "" ${{ env.GITHUB_REF_SLUG }} ${ATTACHMENTS}
